# handlers are ALWAYS executed in the order in which they're in this file
# restarting services should always be the last handler

---
- name: reload systemd
  command: systemctl daemon-reload

- name: restart docker
  service: name=docker enabled=yes state=restarted
