---
- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include: redhat.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 7

- name: Start Docker Service
  service: name=docker enabled=yes state=started
